PHASE 5/An-Online-Marketplace-Django-Project/puddle/conversation/urls.py
from django. urls import path

from .import views


app_name = 'conversation'


urlpatterns =[

    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from . forms import LoginForm

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),

]

PHASE 5/An-Online-Marketplace-Django-Project/puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'


urlpatterns = [
    path('', views.index, name='index'),
]

PHASE 5/An-Online-Marketplace-Django-Project/puddle/item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

PHASE 5/An-Online-Marketplace-Django-Project/puddle/puddle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin



urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/models.py
from django.db import models

# Create your models here.



PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User




class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username','class': 'w-full py-4 px-6 rounded-xl'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password','class': 'w-full py-4 px-6 rounded-xl'}))
    



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Your username','class': 'w-full py-4 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'Your Email Address','class': 'w-full py-4 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Enter Your Password','class': 'w-full py-4 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repeat Password','class': 'w-full py-4 px-6 rounded-xl'}))

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/views.py
from django.shortcuts import render,redirect

from item.models import Category, Item

from .forms import SignupForm
# Create your views here.

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {'categories':categories, 'items': items})

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm

    return render(request, 'core/signup.html',{'form':form})



PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock title %} | ShreyakCart</title>
</head>
<body class="bg-gray-100 text-gray-900">
    <nav class="py-6 px-6 flex justify-between items-center bg-white shadow-md">
        <a href="/" class="text-2xl font-bold text-teal-600">ShreyakCart</a>

        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-teal-500">New Item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-teal-500">Browse</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-600">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-600">Dashboard</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-lg hover:bg-teal-600">Sign Up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-lg hover:bg-gray-600">Log In</a>
            {% endif %}
        </div>
    </nav>

    <main class="px-6 py-8">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="py-8 px-6 bg-gray-800 text-gray-400">
        <div class="container mx-auto flex flex-col md:flex-row justify-between">
            <div class="mb-8 md:mb-0 md:w-2/3">
                <h3 class="mb-4 text-xl font-semibold text-white">About ShreyakCart</h3>
                <p class="text-lg">
                    Welcome to ShreyakCart, your ultimate online destination for all your shopping needs. Explore our diverse categories:
                    <br><br>
                    <b>Clothes:</b> Discover stylish apparel for men, women, and kids, perfect for every occasion.
                    <br>
                    <b>Furniture:</b> Find high-quality, durable furniture that blends beauty with functionality.
                    <br>
                    <b>Toys:</b> Delight your little ones with our safe and engaging toy collection, designed to inspire and entertain.
                    <br><br>
                    At ShreyakCart, we offer quality, convenience, and a seamless shopping experience all in one place!
                </p>
            </div>

            <div class="md:w-1/3">
                <h3 class="mb-4 text-xl font-semibold text-white">Menu</h3>
                <ul class="space-y-3">
                    <li><a href="#" class="text-lg hover:text-teal-400">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg hover:text-teal-400">Contact</a></li>
                    <li><a href="#" class="text-lg hover:text-teal-400">Privacy Policy</a></li>
                    <li><a href="#" class="text-lg hover:text-teal-400">Terms of Use</a></li>
                </ul>
            </div>
        </div>
    </footer>
</body>
</html>

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock title %}


{% block content %}

<h1>The Contact Page</h1>

{% endblock %}

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %} Welcome {% endblock title %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-3xl font-semibold text-center">Newest Items</h2>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for item in items %}
            <div class="bg-white rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="overflow-hidden rounded-t-xl">
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full h-48 object-cover">
                    </div>
                    <div class="p-6">
                        <h2 class="text-xl font-semibold">{{ item.name }}</h2>
                        <p class="text-gray-700 mt-2">Price: ${{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% empty %}
            <p class="col-span-full text-center text-gray-500">No items available at the moment.</p>
        {% endfor %}
    </div>
</div>

<div class="mt-12 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-3xl font-semibold text-center">Categories</h2>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {% for category in categories %}
            <div class="bg-white rounded-xl shadow-lg hover:shadow-xl transition-shadow duration-300">
                <a href="{% url 'category:detail' category.id %}">
                    <div class="p-6">
                        <h2 class="text-xl font-semibold">{{ category.name }}</h2>
                        <p class="text-gray-700 mt-2">{{ category.items.count }} items available</p>
                    </div>
                </a>
            </div>
        {% empty %}
            <p class="col-span-full text-center text-gray-500">No categories available at the moment.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign Up {% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Login</h1>

    <form method="post"  action=".">
        {% csrf_token %}


       <div class="mb-3">
        <label class="inline-block mb-2">Username</label><br>
        {{ form.username }}   
       </div>

       <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br>
        {{ form.password }}   
       </div>

       {% if form.errors or form.non_field_errors %}

       <div class="mb-3 p-6 bg-red-100 rounded-xl"> 
        {% for field in form %}
            {{ field.errors }}

            {% endfor %}

            {{ form.non_field_errors }}

       </div>
       {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>

    </form>

</div>
{% endblock %}

PHASE 5/An-Online-Marketplace-Django-Project/puddle/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign Up {% endblock %}


{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post"  action=".">
        {% csrf_token %}


       <div class="mb-3">
        <label class="inline-block mb-2">Username</label><br>
        {{ form.username }}   
       </div>
       <div class="mb-3">
        <label class="inline-block mb-2">Email</label><br>
        {{ form.email }}   
       </div>
       <div class="mb-3">
        <label class="inline-block mb-2">Password</label><br>
        {{ form.password1 }}   
       </div>
       <div class="mb-3">
        <label class="inline-block mb-2">Repeat Password</label><br>
        {{ form.password2 }}   
       </div>

       {% if form.errors or form.non_field_errors %}
       <div class="mb-3 p-6 bg-red-100 rounded-xl"> 
        {% for field in form %}
            {{ field.errors }}

            {% endfor %}

            {{ form.non_field_errors }}

       </div>
       {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">
            Submit
        </button>

    </form>

</div>
{% endblock %}